// Generated by CIRCT firtool-1.139.0
module Counter4bit(
  input        clock,
               reset,
               io_enable,
  output [3:0] io_count
);

  reg [3:0] regCount;
  always @(posedge clock) begin
    if (reset)
      regCount <= 4'h0;
    else if (io_enable)
      regCount <= regCount + 4'h1;
  end // always @(posedge)
  assign io_count = regCount;
endmodule

